use E_commerce_data;

select customers.customer_city, round(count(order_items.product_id)/ count(distinct orders.order_id),2) as Average_product
from customers
join orders
on customers.customer_id = orders.customer_id
join order_items
on orders.order_id = order_items.order_id
group by customers.customer_city
order by Average_product desc;


select `product category`, round(sum(payments.payment_value) / (select sum(payments.payment_value) from payments)*100,3)  as Percentage_Contributed
from products
join order_items
on products.product_id = order_items.product_id
join payments
on order_items.order_id = payments.order_id
group by `product category`
order by Percentage_Contributed desc;


select product_id, price, count(order_id) as purchase_count
from order_items
group by product_id, price
order by purchase_count desc;	


-- Calculate the total revenue generated by each seller and rank them by revenue.

select order_items.seller_id as Seller, round(sum(order_items.price + order_items.freight_value ),2) as Revenue,
dense_rank() over (order by round(sum(order_items.price + order_items.freight_value ),2) desc ) as seller_rank
from order_items
group by order_items.seller_id ;


-- Calculate the moving average of order value for each customer over their order history.

select orders.customer_id, 
avg(payments.payment_value) over (partition by orders.customer_id order by orders.order_purchase_timestamp rows between unbounded preceding and current row) 
as Moving_Average
from orders
join payments
on orders.order_id = payments.order_id
where orders.order_status = "delivered"
order by Moving_Average desc;

-- Calculate the cumulative sales per month for each year.

with Monthly_Sales as (select year( orders.order_purchase_timestamp) as order_year, month(orders.order_purchase_timestamp) as order_month,
round(sum(order_items.price + order_items.freight_value),2) as Revenue
from orders
join order_items
on orders.order_id = order_items.order_id
where orders.order_status = "delivered"
group by year( orders.order_purchase_timestamp),  month(orders.order_purchase_timestamp))
select order_year, order_month, Revenue,
sum(Revenue) over (partition by order_year order by order_month) as Cumulative_Sales
from Monthly_Sales;

-- Calculate the year-over-year growth rate.

with Rev as (select year(orders.order_purchase_timestamp) as order_year, 
round(sum(payments.payment_value),2) as Revenue,
lag(round(sum(payments.payment_value))) over ( order by year(orders.order_purchase_timestamp)) as Pre
from orders
join payments
on orders.order_id = payments.order_id
group by order_year)

select order_year, Revenue,Pre,
(round((Revenue-Pre)/Pre*100)) as Growth_Percentage
from Rev;


-- Calculate the retention rate of customer defined as the percentage of customers who make another purchase within 6 month of their first purchase.
with First_Order as (select customers.customer_unique_id,
min(orders.order_purchase_timestamp) as First_Purchase
from customers
join orders
on customers.customer_id = orders.customer_id
group by customer_unique_id),
Retained as (select distinct First_Order.customer_unique_id as Retained_Customer
from First_Order
join customers
on First_Order.customer_unique_id = customers.customer_unique_id
join orders
on customers.customer_id = orders.customer_id
where orders.order_purchase_timestamp > First_Order.First_Purchase and
orders.order_purchase_timestamp <= date_add(First_Order.First_Purchase,interval 6 month))
select (round((select count(*) from Retained) / (select count(*) from First_Order)*100,2))as Retention_Rate;


-- Identify the top 3 customer who spent the most money in each year.
with TOP as (select year(orders.order_purchase_timestamp) as Years, customers.customer_unique_id as Customers, sum(payments.payment_value) as Spending,
dense_rank() over (partition by year(orders.order_purchase_timestamp) order by sum(payments.payment_value) desc) as Ranks
from customers
join orders
on customers.customer_id = orders.customer_id
join payments
on orders.order_id = payments.order_id
group by  year(orders.order_purchase_timestamp),customers.customer_unique_id)
select * from TOP where Ranks <= 3;
