use E_commerce_data;
-- 1.  List all unique cities where customers are located.

select distinct(customer_city) from customers;

-- 2. Count the number of orders placed in 2017.

select count(order_id) from orders where year(order_purchase_timestamp) = 2017;

-- 3. Find the total sales per category.
select `product category`, round(sum(payments.payment_value),2) as total_sales
from products
join order_items
on products.product_id = order_items.product_id
join payments
on order_items.order_id = payments.order_id
group by `product category`
order by total_sales desc;

-- 4. Calculate the percentage of order that were paid in installments. 
select round(sum(case when payments.payment_installments >= 1 then 1 else 0 end)/count(*)*100,3)as Installment_Percentage
from payments;

-- 5. Count number of customers from each state.
select customer_state as `Customer State`,count(customer_id) as Customers from customers
group by customer_state 
order by Customers desc;

-- 6. Calculate the number of orders per month in 2018.
select monthname(order_purchase_timestamp) as Month_Name,count(order_id) as Order_Count
from orders
where year(order_purchase_timestamp) = 2018
group by Month_Name;

-- 7. Find the average number of products per order grouped by customer city.
select customers.customer_city, round(count(order_items.product_id)/ count(distinct orders.order_id),2) as Average_product
from customers
join orders
on customers.customer_id = orders.customer_id
join order_items
on orders.order_id = order_items.order_id
group by customers.customer_city
order by Average_product desc;

-- 8. Calculate the percentage of total revenue contributed by each product category.
 select `product category`, round(sum(payments.payment_value) / (select sum(payments.payment_value) from payments)*100,2)  as Percentage_Contributed
from products
join order_items
on products.product_id = order_items.product_id
join payments
on order_items.order_id = payments.order_id
group by `product category`
order by Percentage_Contributed desc;

-- 9. Calculate the total revenue generated by each seller and rank them by revenue.
select order_items.seller_id as Seller, round(sum(order_items.price + order_items.freight_value ),2) as Revenue,
dense_rank() over (order by round(sum(order_items.price + order_items.freight_value ),2) desc ) as seller_rank
from order_items
group by order_items.seller_id
limit 5;

-- 10. Calculate the moving average of order value for each customer over their order history.
select orders.customer_id, 
avg(payments.payment_value) over (partition by orders.customer_id order by orders.order_purchase_timestamp rows between unbounded preceding and current row) 
as Moving_Average
from orders
join payments
on orders.order_id = payments.order_id
where orders.order_status = "delivered"
order by Moving_Average desc;

-- 11. Calculate the cumulative sales per month for each year.
with Monthly_Sales as (select year( orders.order_purchase_timestamp) as order_year, month(orders.order_purchase_timestamp) as order_month,
round(sum(order_items.price + order_items.freight_value),2) as Revenue
from orders
join order_items
on orders.order_id = order_items.order_id
where orders.order_status = "delivered"
group by year( orders.order_purchase_timestamp),  month(orders.order_purchase_timestamp))
select order_year, order_month, Revenue,
sum(Revenue) over (partition by order_year order by order_month) as Cumulative_Sales
from Monthly_Sales;

-- 12. Calculate the year-over-year growth rate.
with Rev as (select year(orders.order_purchase_timestamp) as order_year, round(sum(payments.payment_value),2) as Revenue,
lag(round(sum(payments.payment_value))) over ( order by year(orders.order_purchase_timestamp)) as Pre
from orders
join payments
on orders.order_id = payments.order_id
group by order_year)
select order_year, Revenue,Pre,
from Rev;
(round((Revenue-Pre)/Pre*100)) as Growth_Percentage

-- 13. Calculate the retention rate of customer defined as the percentage of customers who make another purchase within 6 month of their first purchase.
with First_Order as (select customers.customer_unique_id,
min(orders.order_purchase_timestamp) as First_Purchase
from customers
join orders
on customers.customer_id = orders.customer_id
group by customer_unique_id),
Retained as (select distinct First_Order.customer_unique_id as Retained_Customer
from First_Order
join customers
on First_Order.customer_unique_id = customers.customer_unique_id
join orders
on customers.customer_id = orders.customer_id
where orders.order_purchase_timestamp > First_Order.First_Purchase and
orders.order_purchase_timestamp <= date_add(First_Order.First_Purchase,interval 6 month))
select (round((select count(*) from Retained) / (select count(*) from First_Order)*100,2))as Retention_Rate;

-- 14.  Identify the top 3 customer who spent the mot money in each year.
with TOP as (select year(orders.order_purchase_timestamp) as Years, customers.customer_unique_id as Customers, sum(payments.payment_value) as Spending,
dense_rank() over (partition by year(orders.order_purchase_timestamp) order by sum(payments.payment_value) desc) as Ranks
from customers
join orders
on customers.customer_id = orders.customer_id
join payments
on orders.order_id = payments.order_id
group by  year(orders.order_purchase_timestamp),customers.customer_unique_id)
select * from TOP where Ranks <= 3;

-- 15. Identify the state wize top 3 customer who spent the most money in each year.
with TOP as (select year(orders.order_purchase_timestamp) as Years, customers.customer_unique_id as Customers,customers.customer_state as State, sum(payments.payment_value) as Spending,
dense_rank() over (partition by year(orders.order_purchase_timestamp),customers.customer_state order by sum(payments.payment_value) desc) as Ranks
from customers
join orders
on customers.customer_id = orders.customer_id
join payments
on orders.order_id = payments.order_id
group by  year(orders.order_purchase_timestamp),customers.customer_unique_id,customers.customer_state)
select * from TOP where Ranks <= 3;

